baseurl: ""

# use locally localhost instead of 127.0.0.1 so the typekit.net works
host: localhost

markdown: kramdown

exclude:
  - _tools

# destination: ../../public_html/scala2013
# baseurl: www.curryon2015.heathermiller.net
