early_registration_deadline: June 6, 2017
conference_dates: June 18-19<sup>th</sup>, 2017
tickets_sale_due: Friday, May 1<sup>st</sup>, at 5pm CEST
city: Barcelona
previous_editions:
  - 2016
  - 2015

show_program: false
sold_out: false
